# Generated by Django 6.0.2 on 2026-04-21 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_respuestadiagnostico_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestadiagnostico',
            name='administrador',
        ),
        migrations.AddField(
            model_name='respuestadiagnostico',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to=settings.AUTH_USER_MODEL),
        ),
    ]
