
RAZAS_POR_ESPECIE = {
    'Perro': [
        'Labrador Retriever',
        'Pastor Alemán',
        'Golden Retriever',
        'Bulldog Francés',
        'Bulldog Inglés',
        'Poodle',
        'Beagle',
        'Yorkshire Terrier',
        'Dachshund',
        'Chow Chow',
        'Pomerania',
        'Chihuahua',
        'Pug',
        'Cocker Spaniel',
        'Schnauzer Miniatura',
        'Shiba Inu',
        'Akita',
        'Boxer',
        'Doberman Pinscher',
        'Rottweiler',
        'Pastor Australiano',
        'Border Collie',
        'Husky Siberiano',
        'Sabueso',
        'Setter Irlandés',
        'Weimaraner',
        'Vizsla',
        'Pointer Inglés',
        'Spaniel Japonés',
        'Pekingés',
        'Cavalier King Charles Spaniel',
        'Boston Terrier',
        'Whippet',
        'Galgo Italiano',
        'Jack Russell Terrier',
        'Terrier Tibetano',
        'Lhasa Apso',
        'Shih Tzu',
        'Maltés',
        'Bichón Frisé',
        'Caniche Toy',
        'Fox Terrier',
        'Airedale Terrier',
        'Basset Hound',
        'Saint Bernard',
        'Gran Danés',
        'Mastín Inglés',
        'Terranova',
        'Collie',
        'Shar Pei',
        'Staffordshire Bull Terrier',
        'Pit Bull Terrier',
        'Cane Corso',
        'Dogo Argentino',
        'Mastín Español',
        'Otra Raza'
    ],
    'Gato': [
        'Persa',
        'Maine Coon',
        'Siamés',
        'Bengalí',
        'Rajah',
        'Manx',
        'Sphynx',
        'Scottish Fold',
        'Ragdoll',
        'Británico de Pelo Corto',
        'Ruso Azul',
        'Tonkinés',
        'Balinés',
        'Birmano',
        'Bombay',
        'Cornish Rex',
        'Devon Rex',
        'Gato de Pelo Largo',
        'Angora Turco',
        'Bosque de Noruega',
        'Kurilian Bobtail',
        'Munchkin',
        'Sokoke',
        'Turkish Van',
        'Selkirk Rex',
        'LaPerm',
        'California Spangled',
        'Ocicat',
        'Abisinio',
        'Ashera',
        'Serengeti',
        'Savannah',
        'Chausie',
        'Pixie Bob',
        'Gato Doméstico Común',
        'Otra Raza'
    ],
}

ESPECIES = list(RAZAS_POR_ESPECIE.keys())
