# Generated by Django 6.0.2 on 2026-04-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_notificacion_adopcion_notificacion_enlace_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
