# Generated by Django 6.0.2 on 2026-04-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0008_alter_mascota_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Tamaño',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande'), ('Muy Grande', 'Muy Grande')], max_length=50),
        ),
    ]
