# Generated by Django 6.0.3 on 2026-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0009_alter_mascota_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Estado_Salud',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Buena', 'Buena'), ('Regular', 'Regular')], default='Buena', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='Tamaño',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=50),
        ),
    ]
