# Generated by Django 6.0.2 on 2026-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_remove_respuestadiagnostico_administrador_and_more'),
        ('usuarios', '0008_add_nombre_refugio_to_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Criador', 'Criador')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
